### ISSUE TITLE
Add a Monitoring Client (à la syncCto)

### ISSUE THREAD

**Issue by cliffparnitzky** [ContaoMonitoring/monitoring#10]
... for retrieving log files, integrity check results, specials field values, etc.

Authentication is needed, because some information may be secure and should not be accessible without having the permission

**Comment by cliffparnitzky** [comment]
The monitoring server should only get information, that the client provides. So, at first an API ist needed.

Additionally a special client for Contao is needed, but there may also be clients for other systems.

**Comment by Ynda** [comment]
Hi Cliff, great job so far. 
That's exactly what we were looking for.

For effective use the connection to the client modules is necessary. With ~ 35 actively managed Contao installations it is important to be able to act fast on security updates. The current state of the server, the versions of the operating units and the CMS version are very helpful.
Currently the client modules already return a json array with the values. But how is this integrated in the monitoring server? 
I suppose that's why the monitoring-scan-client-updater modules are used.
Is there an approximate timeline?

**Comment by cliffparnitzky** [comment]
Great to hear of your interets and cool to know, there is somebody using the system.

As you can see in the checklist above, the client components with the base sensors are already released.

At server side the [monitoring-scan-client](https://github.com/ContaoMonitoring/monitoring-scan-client) ist the base component for conneting the clients and reading the data. It is currently in development and approximately 75% finished.

After that, the [monitoring-scan-client-updater](https://github.com/ContaoMonitoring/monitoring-scan-client-updater) has to be cretaed. There is already a plan what it should be able to do (offer general updating possibility of fields, adding a CRON job for automatic updating and perhaps a button for manual triggering).

The [monitoring-scan-client-updater-contao-version](https://github.com/ContaoMonitoring/monitoring-scan-client-updater-contao-version) will be the first updater. It will read the `contao.version` from the client and update the field `system` of the monitored system entry.

The  [monitoring-scan-client-updater-additional-infos](https://github.com/ContaoMonitoring/monitoring-scan-client-updater-additional-infos) will be the second updater, that sets field like PHP version, MySQL version, ...

Hope this helps to understand the planned job of the components.

Question to the timeline:

Due to the fact that this project is currently not receiving any financial support, the time schedule is open. Maybe we can find some supporters, to push the process.

**Comment by Ynda** [comment]
Thank you for the detailed presentation. If you need someone to test, I can do that.

**Comment by cliffparnitzky** [comment]
Implemented in a3e1f5d1ceb684fcbb6e6803544406a8797b406e
