### ISSUE TITLE
Provide most system information with login data of remote server

### ISSUE THREAD

**Issue by jscholtysik** [ContaoMonitoring/monitoring#17]
Please provide a possibility that one is able to get most of the system information like

- Contao version / Is Contao up-to-date?
- Is Composer installed or ER2?
- Are the extensions up-to-date? When not, which extensions are not up-to-date?
- Is DB Backup installed?
- PHP-Version
- MySQL-Version

and such other information in an automatic way with login data of the remote server, not as additional Info fields.

**Comment by cliffparnitzky** [comment]
See #3 ... this is provided by https://github.com/ContaoMonitoring/monitoring-additional-infos

An example for a lot of fields ist documented here: https://cliffparnitzky.gitbooks.io/contaomonitoring/content/en/admin/settings/index.html#example-for-additional-info-fields

**Comment by jscholtysik** [comment]
> in an automatic way

Your example in Gitbooks only shows the fields that can be created, but the values have to be inserted manually... I think most of these example fields can be read direct from the system Contao runs or direct from Contao.

Creating the fields in the backend ist one thing, an automatic fillinmg of the values an other.

**Comment by cliffparnitzky** [comment]
Ah okay, didn'd read your request good enough.

Automatically reading information from an monitored could only be done with a separate client.

We should move to: https://github.com/ContaoMonitoring/monitoring/issues/10
