### ISSUE TITLE
Warning: Use of undefined constant TL_INFO

### ISSUE THREAD

**Issue by denniserdmann** [ContaoMonitoring/monitoring#21]
Beim Anlegen eines zweiten Monitoring-Eintrags bekam ich beim Ausführen folgende Warnung:
 
```
Warning: Use of undefined constant TL_INFO - assumed 'TL_INFO' (this will throw an Error in a future version of PHP) in /www/htdocs/[…]/vendor/contao-monitoring/monitoring/system/modules/Monitoring/classes/Monitoring.php on line 360
```

Installation: Contao 4.4.13
Monitoring-Erweiterung: contao-monitoring/bundle-all: "^1.5"
_Ergänzend: PHP: 7.2_

**Comment by cliffparnitzky** [comment]
Die Meldung erscheint, wenn der Debug Modus des Monitoring Systems aktiviert ist (System Einstellungen).

Hier https://github.com/ContaoMonitoring/monitoring/blob/master/system/modules/Monitoring/classes/Monitoring.php#L360 muss `this->log(...)` ausgetauscht werden durch `Message::addInfo(...)`.

**Comment by cliffparnitzky** [comment]
Fixed in ec632272c64297a0512d8f579cdd0d2d9d1687df
